unnecessary_columns = [
    "Customer ID",
    "Latitude",
    "Longitude",
    "Online Security",
    "Online Backup",
    "Multiple Lines",
    "Contract",
    "Number of Referrals",
    "Avg Monthly Long Distance Charges",
    "Avg Monthly GB Download",
    "Device Protection Plan",
    "Premium Tech Support",
    "Payment Method",
    "Internet Type",
    "Paperless Billing",
    "Total Extra Data Charges",
    "Monthly Charge",
    "Unlimited Data",
    "Total Long Distance Charges",
    "Streaming TV",
    "Total Refunds",
    "Streaming Movies",
    "Streaming Music",
    "Churn Reason",
    "Churn Category",
]
