dbtdvdrental:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: db
      port: 5432
      user: postgres
      pass: postgres
      dbname: dvdrental
      schema: analysis

  target: dev
